nodeLinker: node-modules

npmRegistries:
  "https://utk-codeartifacts-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/utk-codeartifact-repo/":
    npmAlwaysAuth: true
    npmAuthToken: ${UTK_CODEARTIFACT_AUTH_TOKEN}

npmRegistryServer: "https://utk-codeartifacts-757269603777.d.codeartifact.us-east-1.amazonaws.com/npm/utk-codeartifact-repo/"

# npmScopes:
#   fortawesome:
#     npmAlwaysAuth: true
#     npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
#     npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
