yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAlwaysAuth: true
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}
