# .github/workflows/change-detection.yml
name: Change Detection

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"
      - "packages/web/**"
      - "packages/shared/**"
      - "**"

  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch a limited number of commits to speed up the checkout
          fetch-depth: 5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get Changed Paths
        id: get-changes
        run: |
          echo "CHANGED_PATHS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      - name: Determine Changed Paths
        id: changes
        run: |
          echo "API_CHANGED=false" >> $GITHUB_ENV
          echo "WEB_CHANGED=false" >> $GITHUB_ENV
          echo "SHARED_CHANGED=false" >> $GITHUB_ENV
          echo "OTHER_CHANGED=false" >> $GITHUB_ENV
          echo $CHANGED_PATHS | grep '^packages/api/' && echo "API_CHANGED=true" >> $GITHUB_ENV || true
          echo $CHANGED_PATHS | grep '^packages/web/' && echo "WEB_CHANGED=true" >> $GITHUB_ENV || true
          echo $CHANGED_PATHS | grep '^packages/shared/' && echo "SHARED_CHANGED=true" >> $GITHUB_ENV || true
          echo $CHANGED_PATHS | grep -v '^packages/' && echo "OTHER_CHANGED=true" >> $GITHUB_ENV || true

      - name: Echo API Changes
        if: env.API_CHANGED == 'true' || env.SHARED_CHANGED == 'true' || env.OTHER_CHANGED == 'true'
        run: echo "Changes detected in API directory."

      - name: Echo Web Changes
        if: env.WEB_CHANGED == 'true' || env.SHARED_CHANGED == 'true' || env.OTHER_CHANGED == 'true'
        run: echo "Changes detected in Web directory."
